// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package about

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/SouichiroTsujimoto/unagi/internal/web/layout"

func Page(meta layout.PageMeta, site layout.Site) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<main class=\"flex flex-col gap-10\"><header class=\"about-header space-y-5\"><img src=\"/static/wuhu1sland-2.png\" alt=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(site.Name)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `about/page.templ`, Line: 11, Col: 20}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" width=\"320\" height=\"320\" class=\"about-avatar h-40 w-40 rounded-2xl object-cover\" decoding=\"async\" fetchpriority=\"high\"><div class=\"space-y-4\"><h1 class=\"text-xl font-semibold tracking-tight\">Tsujimoto Souichiro (@wuhu1sland)</h1><p class=\"about-profile-link text-base-content/55 text-[15px] leading-relaxed\" style=\"--i:1\"><time datetime=\"2005-05-07\">2005/5/7</time>・21歳・学部3回生</p><ul class=\"about-socials\" aria-label=\"Links\"><li style=\"--i:2\"><a href=\"https://x.com/wuhu1sland\" class=\"about-social-link\" rel=\"me noopener noreferrer\" target=\"_blank\">X</a></li><li style=\"--i:3\"><a href=\"https://github.com/SouichiroTsujimoto\" class=\"about-social-link\" rel=\"me noopener noreferrer\" target=\"_blank\">GitHub</a></li><li style=\"--i:3\"><a href=\"https://wuhu1s.land/\" class=\"about-social-link\" rel=\"me noopener noreferrer\" target=\"_blank\">wuhu1s.land</a></li></ul></div></header><section class=\"space-y-4\" aria-labelledby=\"unagi-title\"><h2 id=\"unagi-title\" class=\"text-base font-semibold tracking-tight\">unagi</h2><p class=\"text-base-content/55 text-[15px] leading-relaxed\">個人用のミニマルな技術ブログエンジンです。ワンバイナリのフルスタックGoフレームワーク<a href=\"https://github.com/SouichiroTsujimoto/unigo-template\" class=\"link link-hover text-base-content\">SouichiroTsujimoto/unigo-template</a>で作成しています。</p><p class=\"text-base-content/55 text-[15px] leading-relaxed\"><a href=\"https://github.com/SouichiroTsujimoto/unagi\" class=\"link link-hover text-base-content\">SouichiroTsujimoto/unagi</a>もOSSとして公開しています。気に入ったらforkして使ってみて下さい。</p></section><section class=\"space-y-4\" aria-labelledby=\"subscribe-title\"><h2 id=\"subscribe-title\" class=\"text-base font-semibold tracking-tight\">購読</h2><p class=\"text-base-content/55 text-[15px] leading-relaxed\"><a href=\"/feed.xml\" class=\"link link-hover text-base-content\">RSS</a> から新着記事を購読できます。</p></section></main>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout.Document(meta).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
