// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package home

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/SouichiroTsujimoto/unigo-template/internal/feature/account"
	"github.com/SouichiroTsujimoto/unigo-template/internal/web/layout"
)

func Page(accounts []account.Account) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<main class=\"flex flex-col gap-16\"><header class=\"space-y-4\"><div class=\"flex items-center gap-3\"><img src=\"/static/go-chan-5.png\" alt=\"\" width=\"64\" height=\"64\" class=\"h-12 w-12 rounded-xl object-cover\" decoding=\"async\"><h1 class=\"text-xl font-semibold tracking-tight\">Unigo</h1></div><p class=\"text-base-content/55 text-[15px] leading-relaxed\"><span class=\"text-base-content font-medium\">Island Architecture</span>を採用した、 <span class=\"text-base-content font-medium\">ひとつのバイナリ</span>に収まる <span class=\"text-base-content font-medium\">full-stack Web アプリケーション</span>のテンプレートです。</p></header><section class=\"space-y-5\" aria-labelledby=\"stack-title\"><h2 id=\"stack-title\" class=\"text-base font-semibold tracking-tight\">Stack</h2><ul class=\"text-base-content/55 space-y-2 text-[15px]\"><li><span class=\"text-base-content font-medium\">Echo</span> — HTTP ルーティング</li><li><span class=\"text-base-content font-medium\">templ</span> — HTML テンプレート</li><li><span class=\"text-base-content font-medium\">is-land / Preact</span> — Islands UI</li><li><span class=\"text-base-content font-medium\">SQLite / Bun</span> — 組み込み DB と ORM</li><li><span class=\"text-base-content font-medium\">CertMagic</span> — 自動 HTTPS</li><li><span class=\"text-base-content font-medium\">Tailwind / daisyUI</span> — Utility CSS と UI</li></ul></section><section id=\"example\" class=\"space-y-5 scroll-mt-8\" aria-labelledby=\"example-title\"><div class=\"space-y-2\"><h2 id=\"example-title\" class=\"text-base font-semibold tracking-tight\">Accounts</h2><p class=\"text-base-content/55 text-[15px] leading-relaxed\">Island UI デモンストレーションです。SQLiteに保存されます。</p></div><is-land on:visible><template data-island><account-panel accounts=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(accountsJSON(accounts))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `home/page.templ`, Line: 51, Col: 54}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"></account-panel></template></is-land></section><footer class=\"text-base-content/40 text-sm leading-relaxed\"><code class=\"text-base-content/55\">internal/web/home</code> ,  <code class=\"text-base-content/55\">internal/web/islands</code> ,  <code class=\"text-base-content/55\">internal/feature/account</code> が最小構成の実装例です。</footer></main>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout.Document("Unigo", "home").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
